title: CompSci Blogs
description: "August 2023 to June 2024"
owner_name: rayanesouuuu1234
github_username: rayanesouuuu1234
baseurl: "/studentrep"

remote_theme: pages-themes/modernist@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0


plugins:
- jekyll-remote-theme

future: true
